# About
This notebook encodes the various columns of metadata.csv so that they can be used for a machine learning model.
It creates a new dataframe of the encoded values, drops columns that are redundant, and exports to md_encoded.csv.

Author: Riley Denn

In [1]:
import pandas as pd
import numpy as np
import os
import json
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

In [8]:
with open('../../config.json', 'r') as config_file:
    config = json.load(config_file)

print(config['drive_path'])

DRIVEPATH = config['drive_path']
PATH = DRIVEPATH + "/[EXTERNAL] breakthrough_tech_ai_f24/data"

/Users/rileydenn/Library/CloudStorage/GoogleDrive-rileydenn@gmail.com/.shortcut-targets-by-id/1FsOPywSgK_wZmrVrSTBVi4q8G3Mg_yMJ/Team-Fermata-Energy

In [9]:
md_full = pd.read_csv(PATH + "/metadata.csv")

FOLDER_PATH = PATH + "/building_data"

existing_ids = set()

for folder_name in os.listdir(FOLDER_PATH):
    try:
        existing_ids.add(int(folder_name))
    except ValueError:
        continue

md = md_full[md_full['bldg_id'].isin(existing_ids)]

In [10]:
md.shape

(32000, 15)

In [11]:
md.columns

Index(['bldg_id', 'in.building_america_climate_zone', 'in.iso_rto_region',
       'in.state', 'in.cluster_id', 'in.cluster_name', 'in.heating_fuel',
       'in.interior_lighting_generation', 'in.floor_area_category',
       'in.service_water_heating_fuel', 'in.comstock_building_type',
       'in.comstock_building_type_group', 'in.vintage', 'in.sqft',
       'in.nhgis_county_gisjoin'],
      dtype='object')

In [12]:
md.head()

,bldg_id,in.building_america_climate_zone,in.iso_rto_region,in.state,in.cluster_id,in.cluster_name,in.heating_fuel,in.interior_lighting_generation,in.floor_area_category,in.service_water_heating_fuel,in.comstock_building_type,in.comstock_building_type_group,in.vintage,in.sqft,in.nhgis_county_gisjoin
410,48709,Hot-Dry,NaN,CA,109.0,CA Climate Zone 9,Electricity,gen4_led,200001_500000,Electricity,LargeOffice,Office,1960 to 1969,350000.0,G0600370
494,58658,Cold,NaN,CO,36.0,the Cheyenne-Denver-Colorado Springs Area,NaturalGas,gen2_t8_halogen,100001_200000,Electricity,LargeOffice,Office,Before 1946,150000.0,G0800310
905,105885,Hot-Humid,NaN,HI,42.0,Hawaii,NaturalGas,gen1_t12_incandescent,500001_1mil,NaturalGas,LargeHotel,Lodging,1970 to 1979,750000.0,G1500030
1036,119634,Cold,PJM,IL,82.0,the Chicago to Green Bay and Madison Area,NaturalGas,gen2_t8_halogen,500001_1mil,NaturalGas,LargeHotel,Lodging,1990 to 1999,750000.0,G1700310
1757,205046,Mixed-Humid,NYISO,NY,54.0,the Greater New York City Area,DistrictHeating,gen2_t8_halogen,200001_500000,DistrictHeating,LargeOffice,Office,Before 1946,350000.0,G3600610

In [13]:
md.dtypes

bldg_id                               int64
in.building_america_climate_zone     object
in.iso_rto_region                    object
in.state                             object
in.cluster_id                       float64
in.cluster_name                      object
in.heating_fuel                      object
in.interior_lighting_generation      object
in.floor_area_category               object
in.service_water_heating_fuel        object
in.comstock_building_type            object
in.comstock_building_type_group      object
in.vintage                           object
in.sqft                             float64
in.nhgis_county_gisjoin              object
dtype: object

In [14]:
md.isnull().any()

bldg_id                             False
in.building_america_climate_zone    False
in.iso_rto_region                    True
in.state                            False
in.cluster_id                       False
in.cluster_name                     False
in.heating_fuel                     False
in.interior_lighting_generation     False
in.floor_area_category              False
in.service_water_heating_fuel       False
in.comstock_building_type           False
in.comstock_building_type_group     False
in.vintage                          False
in.sqft                             False
in.nhgis_county_gisjoin             False
dtype: bool

In [15]:
for col in md.columns:
    print(f"{col}: {md[col].unique()}\n"
    f"number of unique values: {np.size(md[col].unique())}\n")

bldg_id: [ 48709  58658 105885 ... 332085 332104 332130]
number of unique values: 32000

in.building_america_climate_zone: ['Hot-Dry' 'Cold' 'Hot-Humid' 'Mixed-Humid' 'Very Cold' 'Subarctic'
 'Mixed-Dry' 'Marine']
number of unique values: 8

in.iso_rto_region: [nan 'PJM' 'NYISO' 'ERCOT' 'MISO' 'SPP' 'CAISO' 'NEISO']
number of unique values: 8

in.state: ['CA' 'CO' 'HI' 'IL' 'NY' 'PA' 'TX' 'AL' 'AK' 'AZ' 'AR' 'DE' 'DC' 'FL'
 'GA' 'ID' 'IN' 'IA' 'KS' 'KY' 'LA' 'ME' 'MD' 'MI' 'MN' 'MS' 'MO' 'MT'
 'NE' 'NV' 'NH' 'NJ' 'NM' 'NC' 'ND' 'OH' 'OK' 'OR' 'SC' 'SD' 'TN' 'UT'
 'VT' 'VA']
number of unique values: 44

in.cluster_id: [109.  36.  42.  82.  54.  63.  74.  75.  53.  85.  81.  76.  37.  71.
  24.  31.   1.  60.  64.  33.  27. 104. 101. 108. 105. 110. 113. 111.
 112. 114.  86.  57.  12.   8.  49.  39.  55.  46.  84.  50.  18.  35.
   9.  26.  66.  68.  17.  47.   3.  51.   4.  56.  78.   0.  43.  30.
  40.  62.  70.  61.  59.  11.  16.  23.  72.  21.  77.  41.  20.  14.
  80.   6.  19.  38.  25.  48.  15.  79.   2.  28.  44.  22.  65.  73.
   5.  83.  34.  69.  58.  32.  45.]
number of unique values: 91

in.cluster_name: ['CA Climate Zone 9' 'the Cheyenne-Denver-Colorado Springs Area' 'Hawaii'
 'the Chicago to Green Bay and Madison Area'
 'the Greater New York City Area'
 'the Cleveland to Pittsburgh Greater Area' 'the Central Gulf Coast Area'
 'the Greater Dallas-Fort Worth Area' 'Central Alabama'
 'Rural Climate Zone 3A' 'the Columbus-Albany Area'
 'the Huntsville-Florence Area' 'Alaska'
 'Northern Arizona and Washington County Utah' 'Rural Southern Arizona'
 'Rural Mountain West' 'the Greater Little Rock Area'
 'the Greater Columbia-Fayetteville-Jefferson City-Joplin-Springfield-Wichita Areas'
 'the Greater Memphis Area' 'Rural Lower Plains-Upper South Appalachia'
 'the Shreveport-Texarkana and Alexandria Area' 'CA Climate Zone 4'
 'CA Climate Zone 1' 'CA Climate Zone 8' 'CA Climate Zone 5'
 'CA Climate Zone 10' 'CA Climate Zone 13' 'CA Climate Zone 11'
 'CA Climate Zone 12' 'CA Climate Zone 14' 'the Colorado Mountains'
 'Rural Rocky Mountains North' 'CO Mountain Rural'
 'Colorado Eastern Plains' 'Rural Counties in the Southwest'
 'the Washington DC to Philadelphia Area' 'Florida'
 'the Tallahassee-Valdosta Area'
 'Rural Climate Zone 2A - Georgia and Florida'
 'the Greater Atlanta and Macon Area'
 'the Knoxville-Chattanooga-Asheville and Greenville, SC Area'
 'Eastern Counties in South Carolina and Georgia' 'Boise-Twin Falls'
 "the Spokane-Coeur d'Alene-Lewiston-Yakima-Wenatchee Area"
 'the Northwestern Utah and Pocatello Area'
 'Small Urban Areas in the Dakotas, Idaho, Montana, and Wyoming'
 'Rural Lower Midwest and High Plains'
 'Indianapolis-St. Louis-Springfield-Peoria'
 'the Evansville and the Shawnee National Forest Area'
 'the Greater Louisville Area' 'the Rural Eastern Climate Zone 5A Area'
 'the Columbus-Dayton-Cincinnati-Lexington Area' 'the Omaha-Lincoln Area'
 'Des Moines, Cedar Rapids, Sioux Falls' 'Rural Midwest Climate Zone 6A'
 'Greater Kansas City'
 'the Greater Nashville and Hopkinsville-Bowling Green Area'
 'the Charleston-Huntington-Beckley Area'
 'the Greater Gulf Coastal Plains'
 'the Burlington Area and Penobscot County' 'Northern New England'
 'MD Eastern Shore and Rural Northern VA'
 'Rural Southern Michigan and the Toledo Area'
 'Rural Upper Michigan, Door and Marinette Counties' 'Rural Midwest North'
 'Greater Minneapolis-St Paul' 'the Duluth-Grand Forks-Fargo Area'
 'the Rochester and La Crosse Area' 'the Jackson-Hattiesburg Area'
 'Greater Columbia and Jefferson City Missouri'
 'Carson City, Storey and Washoe County' 'Las Vegas'
 'the Albuquerque-Santa Fe Area'
 'Rural West Texas and Oklahoma and Southern New Mexico'
 'the El Paso-Las Cruces Area' 'Northern New York'
 'the Rochester-Buffalo and Erie, PA Area'
 'Small Urban Northern New York Areas'
 'Northwestern PA, Ashtabula and Chautauqua Counties'
 'Counties in North Carolina and South Carolina'
 'Rural North and South Carolina Counties'
 'the Greater Central Virginia and Eastern Shore Area'
 'the Bismark and Rapid City Area'
 'the Tulsa to Wichita Falls I-44 Corridor' 'Rural Western Oklahoma'
 'the Portland-Salem-Medford Area' 'Northern Pacific Coast'
 'San Antonio to Waco' 'Brownsville-Corpus Christi-McAllen-Victoria Areas'
 'Amarillo-Lubbock-Abilene-Midland-San Angelo' 'the Texas Border Area']
number of unique values: 91

in.heating_fuel: ['Electricity' 'NaturalGas' 'DistrictHeating' 'FuelOil' 'Propane']
number of unique values: 5

in.interior_lighting_generation: ['gen4_led' 'gen2_t8_halogen' 'gen1_t12_incandescent' 'gen3_t5_cfl']
number of unique values: 4

in.floor_area_category: ['200001_500000' '100001_200000' '500001_1mil' '10001_25000' '25001_50000'
 '50001_100000' '_1000' '1001_5000' '5001_10000' 'over_1mil']
number of unique values: 10

in.service_water_heating_fuel: ['Electricity' 'NaturalGas' 'DistrictHeating' 'Propane' 'FuelOil']
number of unique values: 5

in.comstock_building_type: ['LargeOffice' 'LargeHotel' 'RetailStandalone' 'Warehouse' 'SmallOffice'
 'RetailStripmall' 'SecondarySchool' 'FullServiceRestaurant'
 'QuickServiceRestaurant' 'SmallHotel' 'PrimarySchool' 'MediumOffice']
number of unique values: 12

in.comstock_building_type_group: ['Office' 'Lodging' 'Mercantile' 'Warehouse and Storage' 'Education'
 'Food Service']
number of unique values: 6

in.vintage: ['1960 to 1969' 'Before 1946' '1970 to 1979' '1990 to 1999' '1946 to 1959'
 '1980 to 1989' '2000 to 2012' '2013 to 2018']
number of unique values: 8

in.sqft: [ 350000.  150000.  750000.   17500.   37500.   75000.    1000.    3000.
    7500. 1000000.]
number of unique values: 10

in.nhgis_county_gisjoin: ['G0600370' 'G0800310' 'G1500030' ... 'G5108200' 'G5100510' 'G5100890']
number of unique values: 2077

In [16]:
md.columns

Index(['bldg_id', 'in.building_america_climate_zone', 'in.iso_rto_region',
       'in.state', 'in.cluster_id', 'in.cluster_name', 'in.heating_fuel',
       'in.interior_lighting_generation', 'in.floor_area_category',
       'in.service_water_heating_fuel', 'in.comstock_building_type',
       'in.comstock_building_type_group', 'in.vintage', 'in.sqft',
       'in.nhgis_county_gisjoin'],
      dtype='object')

In [17]:
# Percentage null values for in.iso_rto_region
md["in.iso_rto_region"].isnull().sum() / len(md) * 100

37.30625

In [18]:
md.loc[:, "in.iso_rto_region"] = md["in.iso_rto_region"].fillna("none")

In [19]:
md_encoded = pd.DataFrame()

md_encoded = pd.get_dummies(md, columns=[
    'in.building_america_climate_zone',
    'in.iso_rto_region',
    'in.heating_fuel', 
    'in.interior_lighting_generation',
    'in.service_water_heating_fuel',
    'in.comstock_building_type',
    'in.comstock_building_type_group'
])

# Manually mapping ordinal encoding for year ranges
vintage_mapping = {
    'Before 1946': 0,
    '1946 to 1959': 1,
    '1960 to 1969': 2,
    '1970 to 1979': 3,
    '1980 to 1989': 4,
    '1990 to 1999': 5,
    '2000 to 2012': 6,
    '2013 to 2018': 7
}
md_encoded['in.vintage'] = md['in.vintage'].map(vintage_mapping)

# Label encoding for states
label_encoder = LabelEncoder()
md_encoded["in.state"] = label_encoder.fit_transform(md["in.state"])

# Choose to normalize or not after choosing model
# Scale/normalize sqft values to range between 0 and 1
# scaler = MinMaxScaler()
# md_encoded["in.sqft"] = scaler.fit_transform(md_encoded[["in.sqft"]])

# Drop unwanted columns
columns_to_drop = [
    'in.cluster_name',
    'in.floor_area_category',
    'in.nhgis_county_gisjoin'
]
md_encoded = md_encoded.drop(columns=columns_to_drop)

In [20]:
md_encoded

,bldg_id,in.state,in.cluster_id,in.vintage,in.sqft,in.building_america_climate_zone_Cold,in.building_america_climate_zone_Hot-Dry,in.building_america_climate_zone_Hot-Humid,in.building_america_climate_zone_Marine,in.building_america_climate_zone_Mixed-Dry,...,in.comstock_building_type_SecondarySchool,in.comstock_building_type_SmallHotel,in.comstock_building_type_SmallOffice,in.comstock_building_type_Warehouse,in.comstock_building_type_group_Education,in.comstock_building_type_group_Food Service,in.comstock_building_type_group_Lodging,in.comstock_building_type_group_Mercantile,in.comstock_building_type_group_Office,in.comstock_building_type_group_Warehouse and Storage
410,48709,4,109.0,2,350000.0,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
494,58658,5,36.0,0,150000.0,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
905,105885,10,42.0,3,750000.0,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
1036,119634,13,82.0,5,750000.0,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1757,205046,32,54.0,0,350000.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328562,332060,42,39.0,1,7500.0,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
328585,332083,42,22.0,2,17500.0,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
328587,332085,42,11.0,0,17500.0,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
328606,332104,42,22.0,3,17500.0,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
328632,332130,42,22.0,4,17500.0,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True

In [21]:
md_encoded.to_csv('md_one_hot_encoded.csv', index=False)

# Considerations:
- md["in.state"] was encoded with label encoding, assigning a number value to each state. Could consider target encoding instead, replacing state column with the average energy load for buildings in each state.    

- md["in.nhgis_county_gisjoin"] - represents coordinates, used for mapping weather data to spatial coordinates. Could use plotly or geographic plotly for visualization. Can be dropped for model dev.    

- md["in.iso_rto_region"] has ~37% nulls. Changed nans to the string "none" then one hot encoded. ISO RTO reigons refer to the governing agency and is reigonal, so has correlation to other geographic features. May not be needed for model but is included in md_encoded just in case.

- md["in.comstock_building_type"] is similar to the column md["in.comstock_building_type_group"], which is a simplified version of this feature with fewer unique values, while still capturing the various building types at a broad level. Both have been included in md_encoded. For modeling, experiment with using both or one or the other.

- md_encoded["in.sqft"] left as is - can choose to normalize sqft or not after choosing model.  
Code to normalize sqft values to range between 0 and 1:
```python
scaler = MinMaxScaler()  
md_encoded["in.sqft"] = scaler.fit_transform(md_encoded[["in.sqft"]])